package product

import "encoding/json"

// CollaborationSchemas owns the additive closed contracts. Shared discussion
// definitions preserve the shipped MR identity, user and note representation.
func CollaborationSchemas() map[string]string {
	type object = map[string]any
	closed := func(required []string, properties object) object {
		return object{"type": "object", "additionalProperties": false, "required": required, "properties": properties}
	}
	positive := func() object { return object{"type": "integer", "minimum": 1} }
	ref := func(name string) object { return object{"$ref": "mr-discussions.schema.json#/$defs/" + name} }
	users := func() object { return object{"type": "array", "maxItems": 1000, "items": ref("user")} }
	issue := closed([]string{"id", "iid", "project_id", "project", "web_url", "updated_at"}, object{
		"id": positive(), "iid": positive(), "project_id": positive(), "project": ref("project_identity"),
		"web_url":    object{"type": "string", "format": "uri", "pattern": "^https://"},
		"updated_at": object{"type": "string", "format": "date-time"},
	})
	thread := closed([]string{"id", "project_id", "issue_id", "issue_iid", "individual_note", "resolvable", "resolved", "resolution_state", "notes"}, object{
		"id":         object{"type": "string", "minLength": 1, "maxLength": 256},
		"project_id": positive(), "issue_id": positive(), "issue_iid": positive(),
		"individual_note": object{"type": "boolean"}, "resolvable": object{"type": "boolean"}, "resolved": object{"type": "boolean"},
		"resolution_state": object{"enum": []string{"not_resolvable", "resolved", "unresolved"}},
		"notes":            object{"type": "array", "minItems": 1, "maxItems": 1000, "items": ref("note")},
	})
	reviewers := closed([]string{"availability", "users"}, object{
		"availability": object{"enum": []string{"available", "unknown"}}, "users": users(),
	})
	approvals := closed([]string{"availability", "state", "tier", "approved_by"}, object{
		"availability": object{"enum": []string{"available", "unavailable"}},
		"reason":       object{"enum": []string{"access_denied", "not_found_or_unsupported"}},
		"state":        object{"enum": []string{"approved", "not_approved", "unknown"}}, "tier": object{"const": "unknown"},
		"approvals_required": object{"type": "integer", "minimum": 0}, "approvals_left": object{"type": "integer", "minimum": 0},
		"approved_by": users(),
	})
	approvals["allOf"] = []any{object{
		"if": object{"properties": object{"availability": object{"const": "unavailable"}}},
		"then": object{
			"required":   []string{"reason"},
			"properties": object{"state": object{"const": "unknown"}, "approved_by": object{"maxItems": 0}},
			"not":        object{"anyOf": []any{object{"required": []string{"approvals_required"}}, object{"required": []string{"approvals_left"}}}},
		},
		"else": object{"not": object{"required": []string{"reason"}}},
	}}
	schemas := map[string]object{
		"issue-discussions": closed([]string{"issue", "discussions"}, object{"issue": issue, "discussions": object{"type": "array", "maxItems": 1000, "items": thread}}),
		"mr-approvals":      closed([]string{"mr", "reviewers", "approvals"}, object{"mr": ref("mr_identity"), "reviewers": reviewers, "approvals": approvals}),
	}
	out := map[string]string{}
	for name, schema := range schemas {
		schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
		schema["$id"] = "https://glab-axi.invalid/schema/ux-v1/" + name + ".schema.json"
		schema["$comment"] = "Generated by go run ./cmd/gen-product; edit internal/product/collaboration_schema.go."
		schema["title"] = "glab-axi/ux-v1 " + name + " data"
		body, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			panic(err)
		}
		out[name+".schema.json"] = string(body) + "\n"
	}
	return out
}
