package product

import "encoding/json"

// MRWriteSchemas owns generation of the two MR write data contracts. Existing
// native-v1 and unrelated resource schemas are not regenerated here.
func MRWriteSchemas() map[string]string {
	closed := func(required []string, properties map[string]any) map[string]any {
		return map[string]any{"type": "object", "additionalProperties": false, "required": required, "properties": properties}
	}
	positive := map[string]any{"type": "integer", "minimum": 1}
	ids := map[string]any{"type": "array", "minItems": 1, "maxItems": 20, "uniqueItems": true, "items": positive}
	text := map[string]any{"type": "string", "minLength": 1, "maxLength": 4096}
	creation := closed(nil, map[string]any{"assignee_ids": ids, "reviewer_ids": ids, "milestone_id": positive, "draft": map[string]any{"const": true}})
	delete(creation, "required")
	write := closed([]string{"action", "outcome", "iid", "web_url", "source_branch", "target_branch", "head_sha", "expected_state", "attempts", "provider_revision_enforced"}, map[string]any{
		"action":  map[string]any{"enum": []string{"comment", "note", "close", "reopen"}},
		"outcome": map[string]any{"enum": []string{"created", "observed", "unchanged", "unknown", "rejected", "refused"}},
		"iid":     positive, "web_url": text, "source_branch": text, "target_branch": text,
		"head_sha":                   map[string]any{"type": "string", "pattern": "^(?:[0-9a-f]{40}|[0-9a-f]{64})$"},
		"expected_state":             map[string]any{"enum": []string{"opened", "closed"}},
		"observed_state":             map[string]any{"enum": []string{"opened", "closed"}},
		"attempts":                   map[string]any{"type": "integer", "minimum": 0, "maximum": 1},
		"provider_revision_enforced": map[string]any{"const": false},
		"note_id":                    positive, "note_url": text,
	})
	schemas := map[string]map[string]any{
		"mr-write": closed([]string{"write"}, map[string]any{"write": write}),
		"mr-ensure": closed([]string{"mr", "action"}, map[string]any{
			"mr":       map[string]any{"$ref": "resources.schema.json#/$defs/mr"},
			"action":   map[string]any{"enum": []string{"created", "updated", "unchanged", "reconciled_create", "reconciled_update"}},
			"creation": creation,
		}),
	}
	result := map[string]string{}
	for name, schema := range schemas {
		schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
		schema["$id"] = "https://glab-axi.invalid/schema/ux-v1/" + name + ".schema.json"
		schema["$comment"] = "Generated by cmd/gen-product from internal/product/mr_write_schema.go."
		schema["title"] = "glab-axi/ux-v1 " + name + " data"
		encoded, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			panic(err)
		}
		result[name] = string(encoded) + "\n"
	}
	return result
}
