package product

import (
	"encoding/json"
	"sort"
)

// PlanningSchemas is the owner for the additive planning data contracts.
// cmd/gen-product writes these assets alongside registry-owned help.
func PlanningSchemas() map[string]string {
	type object = map[string]any
	str := func(max int) object { return object{"type": "string", "maxLength": max} }
	enum := func(values ...string) object { return object{"type": "string", "enum": values} }
	constant := func(value any) object { return object{"const": value} }
	obj := func(properties object) object {
		keys := make([]string, 0, len(properties))
		for k := range properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		return object{"type": "object", "additionalProperties": false, "required": keys, "properties": properties}
	}
	ref := func(name string) object { return object{"$ref": "#/$defs/" + name} }
	array := func(name string) object { return object{"type": "array", "maxItems": 1000, "items": ref(name)} }
	nullable := func(value object) object { return object{"anyOf": []any{value, object{"type": "null"}}} }
	integer := object{"type": "integer", "minimum": 1}
	url := object{"type": "string", "format": "uri", "pattern": "^https://", "maxLength": 2048}
	defs := object{
		"scope": obj(object{"kind": enum("project", "group"), "id": str(128), "full_path": str(1024), "url": url}),
		"board": obj(object{"id": integer, "name": str(1024), "url": url, "hide_backlog_list": object{"type": "boolean"}, "hide_closed_list": object{"type": "boolean"}}),
		"label": obj(object{"id": str(128), "title": str(1024), "color": object{"type": "string", "pattern": "^#[0-9a-fA-F]{6}$"}}),
		"list":  obj(object{"id": integer, "title": str(1024), "type": enum("backlog", "closed", "label", "assignee", "milestone", "iteration", "status"), "position": nullable(object{"type": "integer"}), "label": nullable(ref("label"))}),
		"item":  obj(object{"id": str(128), "iid": integer, "title": str(1024), "state": enum("opened", "closed"), "url": url, "type": str(128), "namespace": str(1024), "project": nullable(ref("scope"))}),
		"field": obj(object{"name": str(128), "kind": enum("fixed", "widget")}),
	}
	ordering := obj(object{
		"acknowledged": constant(true), "provider_schema_baseline": constant("GitLab EE 19.3.0"),
		"provider_tiers": constant("Free, Premium, Ultimate; advanced board/list features are tier-dependent"),
		"host":           str(253), "scope_kind": enum("project", "group"), "scope_path": str(1024),
		"board_id": integer, "list_id": integer, "possible_effect": constant(planningOrderingEffect),
		"outcome": constant("may_have_occurred"), "delegate_attempts": object{"type": "integer", "minimum": 1, "maximum": 10},
	})
	defs["ordering"] = ordering
	shapes := map[string]object{
		"board-list":             {"boards": array("board")},
		"board-view":             {"board": ref("board"), "lists": array("list"), "membership": constant("provider_board_and_list_filters"), "scope_filters": constant("provider_applied_not_projected")},
		"board-issues":           {"ordering": ref("ordering"), "board": ref("board"), "list": ref("list"), "issues": array("item"), "membership": constant("provider_board_and_list_filters"), "scope_filters": constant("provider_applied_not_projected")},
		"work-item-fields":       {"work_item": ref("item"), "fields": array("field"), "custom_field_definitions": constant("not_exposed")},
		"work-item-hierarchy":    {"work_item": ref("item"), "parent": nullable(ref("item")), "children": array("item"), "depth": constant(1)},
		"board-ordering-receipt": {"board_ordering": ref("ordering")},
	}
	out := map[string]string{}
	for name, properties := range shapes {
		if name != "board-ordering-receipt" {
			properties["scope"] = ref("scope")
			properties["visibility"] = constant("authorized_only")
		}
		schema := obj(properties)
		schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
		schema["$id"] = "https://glab-axi.invalid/schema/ux-v1/" + name + ".schema.json"
		schema["$comment"] = "Generated by go run ./cmd/gen-product; edit internal/product/planning_schema.go."
		schema["title"] = "glab-axi/ux-v1 " + name + " data"
		schema["$defs"] = defs
		body, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			panic(err)
		}
		out[name+".schema.json"] = string(body) + "\n"
	}
	return out
}
