package product

import (
	"encoding/json"
	"sort"
)

// StackSchema owns the generated, closed local stack output contract.
func StackSchema() string {
	type obj = map[string]any
	object := func(props obj) obj {
		keys := make([]string, 0, len(props))
		for k := range props {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		return obj{"type": "object", "additionalProperties": false, "required": keys, "properties": props}
	}
	str := func(n int) obj { return obj{"type": "string", "maxLength": n} }
	enum := func(s ...string) obj { return obj{"type": "string", "enum": s} }
	node := object(obj{"name": str(1024), "parent": str(1024), "head": str(64), "status": enum("ready", "missing", "missing_parent", "diverged"), "mr": obj{"type": "integer", "minimum": 0}, "current": obj{"type": "boolean"}, "mr_state": enum("not_observed", "unbound", "opened"), "mr_url": str(2048)})
	stack := object(obj{"name": str(64), "base": str(1024), "base_head": str(64), "current_branch": str(1024), "action": enum("view", "registered", "unchanged", "checked_out"), "mr_observation": enum("not_requested", "observed", "partial"), "total_branches": obj{"type": "integer", "minimum": 1, "maximum": 32}, "branches": obj{"type": "array", "maxItems": 32, "items": node}})
	schema := object(obj{"stack": stack})
	schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
	schema["$id"] = "https://glab-axi.invalid/schema/ux-v1/stack.schema.json"
	schema["$comment"] = "Generated by go run ./cmd/gen-product; edit internal/product/stack_schema.go."
	b, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		panic(err)
	}
	return string(b) + "\n"
}
