package product

import "encoding/json"

// VariableSchemas owns the generated closed CI-variable data contracts.
func VariableSchemas() map[string]string {
	object := func(required []string, properties map[string]any) map[string]any {
		return map[string]any{"type": "object", "additionalProperties": false, "required": required, "properties": properties}
	}
	str := map[string]any{"type": "string"}
	boolean := map[string]any{"type": "boolean"}
	metadata := object([]string{"key", "environment_scope", "variable_type", "class", "masked", "hidden", "protected", "raw"}, map[string]any{
		"key": map[string]any{"type": "string", "pattern": "^[A-Za-z0-9_]{1,255}$"}, "environment_scope": map[string]any{"type": "string", "minLength": 1, "maxLength": 255},
		"variable_type": map[string]any{"enum": []string{"env_var", "file"}}, "class": map[string]any{"enum": []string{"ordinary", "protected", "masked", "hidden"}},
		"masked": boolean, "hidden": boolean, "protected": boolean, "raw": boolean,
	})
	list := object([]string{"variables", "values_disclosed"}, map[string]any{"variables": map[string]any{"type": "array", "maxItems": 1000, "items": metadata}, "values_disclosed": map[string]any{"const": false}})
	receipt := object([]string{"action", "outcome", "project_id", "project_url", "key", "environment_scope", "atomic_precondition", "mutation_attempted"}, map[string]any{
		"action": map[string]any{"enum": []string{"set", "delete", "unchanged"}}, "outcome": map[string]any{"enum": []string{"not_applied", "precondition_observed", "postcondition_observed", "ambiguous"}},
		"project_id": map[string]any{"type": "integer", "minimum": 1}, "project_url": str, "key": str, "environment_scope": str, "atomic_precondition": map[string]any{"const": false}, "mutation_attempted": boolean, "state": metadata,
	})
	schemas := map[string]map[string]any{"ci-variable-list": list, "ci-variable-mutation": object([]string{"variable"}, map[string]any{"variable": receipt})}
	out := map[string]string{}
	for name, schema := range schemas {
		schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
		schema["$id"] = "https://github.com/M00NLIG7/glab-axi/schema/ux-v1/" + name + ".schema.json"
		schema["$comment"] = "Generated by go run ./cmd/gen-product; edit internal/product/variables_schema.go."
		data, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			panic(err)
		}
		out[name] = string(data) + "\n"
	}
	return out
}
